#Номенклатурни данни за заболявания, които изискват диспансерно наблюдение
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('А 07.8','Други протозойни чревни болести');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('А 15.0','Туберкулоза на белите дробове');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('А 15.3','Туберкулоза на белите дробове, потвърдена с неуточнени методи');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('A 16.0','Туберкулоза на б. дробове с отр. бакт. и хист изсл.');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('В 18.1-18.8','Хроничен вирусен хепатит B');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('B 67.0','Ехинококоза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('B 75','Трихинелоза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('B 80','Ентеробиоза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 22','Злокачествено новообразувание на черния дроб');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 40','Остеосарком');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 64','Злокачествено новообразувание на бъбрека');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 69','Злокачествено новообразувание на окото');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('С 71.0','Злокачествено новообразувание на главния мозък');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 72.0','Злокачествено новообразувание на гръбначн. мозък');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('С 75.1','Злокачествено новообразувание на хипофизата');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 81.9','Болест на Hodgking');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 91.1','Лимфоидна левкемия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('С 92.1','Хронична миелоидна левкемия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('C 95.9','Левкемия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 50.0','Жеязонедоимъчни анемии, от хр.загуба на кръв');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D50.9','Жеязонедоимъчна анемия, неуточнена');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 56.1 -9','Таласемия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 58-59','Хемолитични анемии');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 60-61','Апластична анемия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 61.0','Конституционална апластична анемия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 66','Вроден дефицит на фактор VIII');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 68','Хемофилия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 69.0','Пурпура и др. хеморагични състояния');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('D 69.6','Тромбоцитопения, неуточнена');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 03.1','Вроден хипотиреоидизъм');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 04.0','Нетоксична дифузна гуша');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 05.0','Тиреотоксикоза с дифузна гуша');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 06.3','Тиреоидит на Хашимото');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Е 07.1','Дисхормонална гуша');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 10.4','Инсулинозависим диабет с неврологични усложн.');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 10.9','Инсулинозависим диабет');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 22','Хиперфункция на хипофизата');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Е 23.2','Безвкусен диабет');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Е 24.0','Синдром на Cushing с хипофизарен произход');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Е 28.2','Синдром на поликистоза на яйчниците');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 30.0','Закъснял пуберитет');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('E 34.3','Нанизъм некласифициран другаде');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Е 84.0','Муковисцидоза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 20.0','Шизофрении');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 31','Биполярно афективно разстройство');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 32','Депресивен епизод');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 40','Фобийни тревожни разстройства');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 41','Други тревожни разстройства');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 44','Дисоциативни /конверсионни/ разстройства');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 48','Други невротични разстройства');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 84','Генерализирани разст. в развитието детски аутизъм');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 90','Хиперкинетични разстройства');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('F 98','Др. поведенчески и емоционални разстройства');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 04.8','Енцефалити');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 11.0','Вродена непрогресираща атаксия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 12.0','Детска спинална мускулна атрофия, I тип');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 35','Множествена склероза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 40.0-8','Епилепсия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 54.1','Увреждане на лумбосакралния плексус');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 71','Първични мускулни увреждания');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 80.0-8','Детска церебрална парализа');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 83.0','Други паралитични синдроми');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 91.0','Хидроцефалия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('G 93.1','Др. увреждане на главния мозък');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 26.0','Детска, юношеска катаракта');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 33.5','Други форми на отлепване на ретината');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 40.0','Глаукома');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 40.5','Вторич. глаукома, дължаща се на болести на окото');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 46-47','Болести на зрителния нерв');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 54.0','Слепота и намалено зрение');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 54.1','Слепота на едно око и намал. зрение на другото');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 54.4','Слепота на едното око');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 54.2','Намаление на зрението на двете очи');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 54.5','Намаление на зрението на едното око');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 65.2','Негнойно възпаление на средното ухо');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 90','Глухота');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('H 93.3','Болести на слуховия нерв');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 00','Ревматизъм без засягане на сърцето');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 09','Други ревматични болести на сърцето');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 10','Есенциална /първична/ хипертония');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 11','Хипертонична болест на сърцето');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 34.0','Митрална (клапна) инсуфициенция');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 34.1','Митрален (клапен) пролапс');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 35.0','Аортна (клапна) стеноза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 44.2','Атриовентрикуларен блок, пълен');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 45.6','Синдром на преждевременното възбуждане');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('I 51.8','Други неточно определени болести на сърцето');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('J 30.1','Алергичен ринит, причинен от полени');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('J 30.2','Други сезонни алергични ринити');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('J 30.3','Други алергични ринити');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('J 41.0','Обикновен хроничен бронхит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('J 44.0','Хр. обструктивна белодробна болест с ОРИДДП');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('J 45.0','Астма');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('J 45.1','Неалергична астма');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K 25','Язва на стомаха ');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K 26','Язва на дуоденума');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K 51.0','Улцерозен колит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K 73','Хр. персистиращ хепатит, некласифиц. другаде');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K 80.4','Камъни на жлъчните пътища с холецистит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K 86.1','Хроничен панкреатит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K90.0','Цьолиакия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('K 90.8','Други нарушения в резорбцията на червата');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('L 40.0','Псориазис вулгарис');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('М 00','Пиогенен артрит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 02','Реактивни артропатии');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 08.0','Юношески ревматоиден артрит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 08.8','Други юношески артрити');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 32.8','Други форми на дисеминиран Lupus erythematodes');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 45','Анкилозиращ спондилит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 47','Спондилоза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 50.0','Увреждане на междупрешлените дискове');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('M 91-92','Юношеска остеохондроза на таза, бедр.кост и др.');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('N 03','Хроничен нефритен синдром');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('N 04','Нефрозен синдром ');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('N 05','Нефритен синдром, неуточнен');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('N 11','Хроничен тубулоинтестициален нефрит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('N 10-N 16','Остър и хроничен пиелонефрит');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('N 18','Хронична бъбречна недостатъчност');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('N 20','Нефролитиаза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 05.0','Спина бифида');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 05.2','Лумбална spina bifida с хидроцефалия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 11.2','Микрофталм');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 16.4','Други вродени аномалии на средното ухо');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 20.3','Vcc дискордантно свързване на камерите с артерии');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 21.0','Междукамерен септален дефект');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 21.1','Междупредсърден септален дефект');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 21.2','Предсърднокамерен септален дефект');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q21.3','Тетралогия на Fallo');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 22.0','Атрезия на клапата на белодробната артерия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 22.1','Вродена стеноза на клапата на белодр. артерия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 22.4','Вродена стеноза на трикуспидалната клапа');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 23.0','Вродена стеноза на аортната клапа');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 23.2','Вродена митрална стеноза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 23.3','Вродена митрална инсуфициенция');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 24.0','Dextrocardia');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 24.8','Други уточнени вродени аномалии на сърцето');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 25.0','Отворен дуктус артериозус');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 25.1','Коарктация на аортата');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 25.6','Стеноза на белодробната артерия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 26','Вродени аномалии на големите вени');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 26.8','Други вродени аномалии на големите вени');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 43.0','Други вродени аномалии на червата');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 61.1','Бъбречна поликистоза, инфантилен тип');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 61.4','Бъбречна дисплазия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 62.1','Атрезия и стеноза на уретера');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 65.0','Вродена луксация на бедрото, едностранна');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 77.4','Ахондроплазия');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 78.0-2','Други остеохондродисплазии');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 80.2','Ихтиоза');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 91.0','Синдром на Edwards');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('Q 96','Синдром на Turner');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('T 90','Последици от травми на главата');
INSERT INTO school_health.dispensary_observation_illness_type (dispensary_observ_illness_type_code, dispensary_observ_illness_type_name) VALUES ('T 95.0','Последици от термични и химични изгаряния');

