#Номенклатурни данни за общини
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR01','Аврен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO59','Долна баня');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS01','Айтос');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR02','Аксаково');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLS01','Алфатар');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO54','Антон');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('TGV02','Антоново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV02','Априлци');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KRZ02','Ардино');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV01','Асеновград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB03','Балчик');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML02','Баните');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG01','Банско');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ03','Батак');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN03','Белене');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG02','Белица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ04','Белово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID01','Белоградчик');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR04','Белослав');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON02','Берковица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG03','Благоевград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL04','Бобов дол');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL05','Бобошево');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO06','Божурище');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID03','Бойница');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON04','Бойчиновци');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('JAM03','Болярово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML05','Борино');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC05','Борован');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE03','Борово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO07','Ботевград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR04','Братя Даскалови');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ06','Брацигово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID06','Брегово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PER08','Брезник');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV07','Брезово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON07','Брусарци');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS04','Бургас');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE04','Бяла');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR05','Бяла');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC08','Бяла Слатина');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR06','Варна');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU23','Велики Преслав');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR04','Велико Търново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ08','Велинград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU07','Венец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE05','Ветово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR08','Ветрино');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID09','Видин');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC10','Враца');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON11','Вълчедръм');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR09','Вълчи дол');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU10','Върбица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON12','Вършец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('GAB05','Габрово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB12','Генерал Тошево');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON14','Георги Дамяново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLS07','Главиница');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO09','Годеч');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO10','Горна Малина');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR06','Горна Оряховица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG11','Гоце Делчев');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID15','Грамада');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN08','Гулянци');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR37','Гурково');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR07','Гълъбово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG13','Гърмен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE08','Две могили');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML09','Девин');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR14','Девня');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KRZ08','Джебел');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV09','Димитровград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID16','Димово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB15','Добрич-селска');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB28','Добрич');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN10','Долна Митрополия');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN11','Долни Дъбник');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR13','Долни чифлик');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML10','Доспат');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO16','Драгоман');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('GAB12','Дряново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLS10','Дулово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL48','Дупница');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR16','Дългопол');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR13','Елена');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO17','Елин Пелин');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('JAM07','Елхово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO18','Етрополе');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RAZ11','Завет');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PER19','Земен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR14','Златарица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO47','Златица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML11','Златоград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV11','Ивайловград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE13','Иваново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN23','Искър');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RAZ14','Исперих');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO20','Ихтиман');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB17','Каварна');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR12','Казанлък');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLS15','Кайнарджа');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV12','Калояново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS08','Камено');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU18','Каолиново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV13','Карлово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS09','Карнобат');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU19','Каспичан');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KRZ14','Кирково');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN39','Кнежа');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PER22','Ковачевци');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC20','Козлодуй');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO24','Копривщица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO25','Костенец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO26','Костинброд');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLV11','Котел');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL27','Кочериново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG28','Кресна');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC21','Криводол');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV39','Кричим');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KRZ15','Крумовград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB20','Крушари');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RAZ16','Кубрат');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV42','Куклен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID22','Кула');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KRZ16','Кърджали');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL29','Кюстендил');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN16','Левски');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ14','Лесичово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV17','Летница');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV18','Ловеч');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RAZ17','Лозница');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON24','Лом');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV19','Луковит');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV15','Лъки');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV17','Любимец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR20','Лясковец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML16','Мадан');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV18','Маджарово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID25','Макреш');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS12','Малко Търново');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV17','Марица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON26','Медковец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC27','Мездра');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC28','Мизия');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV19','Минерални бани');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO56','Мирково');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KRZ21','Момчилград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON29','Монтана');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR22','Мъглиж');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL31','Невестино');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML18','Неделино');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS15','Несебър');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU21','Никола Козлево');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR38','Николаево');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN21','Никопол');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLV16','Нова Загора');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU22','Нови пазар');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID30','Ново село');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('TGV22','Омуртаг');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('TGV23','Опака');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR23','Опан');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC31','Оряхово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR24','Павел баня');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR22','Павликени');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ19','Пазарджик');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ20','Панагюрище');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PER32','Перник');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV40','Перущица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG33','Петрич');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ21','Пещера');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO55','Пирдоп');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN24','Плевен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV22','Пловдив');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR26','Полски Тръмбеш');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS17','Поморие');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('TGV24','Попово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN27','Пордим');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO34','Правец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS27','Приморско');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR24','Провадия');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV23','Първомай');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR27','Раднево');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PER36','Радомир');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RAZ26','Разград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG37','Разлог');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ24','Ракитово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV25','Раковски');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL38','Рила');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV26','Родопи');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC32','Роман');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML27','Рудозем');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS18','Руен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID33','Ружинци');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE27','Русе');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV28','Садово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO39','Самоков');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RAZ29','Самуил');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG40','Сандански');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL41','Сапарева баня');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG42','Сатовча');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV28','Свиленград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR28','Свищов');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO43','Своге');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('GAB29','Севлиево');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ29','Септември');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLS31','Силистра');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV29','Симеоновград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG44','Симитли');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLS32','Ситово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLV20','Сливен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO45','Сливница');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE33','Сливо поле');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML31','Смолян');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU25','Смядово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS21','Созопол');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV43','Сопот');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SOF46','Столична');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS06','Средец');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV41','Стамболийски');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV30','Стамболово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR31','Стара Загора');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR31','Стражица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('JAM22','Стралджа');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ32','Стрелча');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG49','Струмяни');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VAR26','Суворово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS23','Сунгурларе');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VTR32','Сухиндол');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV33','Съединение');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PAZ39','Сърница');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLV24','Твърдица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB27','Тервел');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV33','Тетевен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV32','Тополовград');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KNL50','Трекляно');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV34','Троян');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PER51','Трън');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('GAB35','Трявна');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('JAM25','Тунджа');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SLS34','Тутракан');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('TGV35','Търговище');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV36','Угърчин');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG52','Хаджидимово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VRC35','Хайредин');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV33','Харманли');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('HKV34','Хасково');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PDV37','Хисаря');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU11','Хитрино');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RAZ36','Цар Калоян');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BGS13','Царево');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('RSE37','Ценово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO57','Чавдар');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SFO58','Челопеч');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SML38','Чепеларе');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('PVN37','Червен бряг');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('KRZ35','Черноочене');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON36','Чипровци');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SZR36','Чирпан');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('VID37','Чупрене');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('DOB29','Шабла');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('SHU30','Шумен');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('LOV38','Ябланица');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('MON38','Якимово');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('BLG53','Якоруда');
INSERT INTO school_health.municipality (municipality_code, municipality_name) VALUES ('JAM26','Ямбол');

