#Номенклатурни данни за заболявания и аномалии
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('2', 'Туберкулоза (010-018)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('3', 'Злокачествени новообразувания (140-208)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('4', 'Болести на щитовидната жлеза (240-246)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('5', 'Захарна болест (диабет) (250)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('6', 'Затлъстяване (278)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('7', 'Болести на кръвта и кръвотворните органи (280-289)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('8', 'Неврози (300)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('9', 'Специални симптоми и синдроми (заекване, тикове, анорексия, енурезис, стереотипи) (307)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('10', 'Специфично забавяне в развитието (315)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('11', 'Олигофрения (317-319)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('12', 'Детска церебрална парализа (343)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('13', 'Епилепсия (345)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('14', 'Нарушения на рефракцията и акомодацията (367)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('15', 'Смущения в зрението (368)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('16', 'Слепота и намалено зрение (369)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('17', 'Болести на ухото и на мастоидния израстък (380-389)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('18', 'в т.ч. Глухота (389)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('19', 'Остър ревматизъм и хронична ревмат. кардиопатия (390-398)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('20', 'Хипертонична болест (401-405)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('21', 'Хронични заболявания на тонзилите и аден. вегетации (474)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('22', 'Алергичен ринит (477)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('23', 'Пневмония (480)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('24', 'Хроничен бронхит (491)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('25', 'Астма (493)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('26', 'Язва на стомаха и дванадесетопръстника (531-532)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('27', 'Гастрит и дуоденит (535)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('28', 'Абдоминална херния (550-553)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('29', 'Хроничен хепатит (571.4)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('30', 'Остър и хроничен гломерулонефрит (580-583)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('31', 'Остър и хроничен пиелонефрит (590)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('32', 'Камъни в бъбрека и уретера (592)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('33', 'Кръвотечения от половите органи и смущения на менструацията (626)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('34', 'Артропатии и сродни заболявания (710-719)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('35', 'Плоско стъпало, придобито (734)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('36', 'Гръбначни изкривявания (737)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('37', 'Вродени аномалии (740-759)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('38', 'в т.ч. на сърдечно съдовата система (745-747)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('39', 'крипторхизъм (752)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('40', 'Късни последици от травми и отравяния (905-909)');
INSERT INTO school_health.diseases_and_abnorm_type (diseases_and_abnorm_type_code, diseases_and_abnorm_type_name) VALUES ('41', 'Други');

